fights:
  countdown:
    # seconds
    time: 5
    sound: NOTE_PLING
    message: ""

  # seconds
  end-teleport-wait: 3

  # -1 = disable
  # 0 = no teleport allowed
  max-teleport-distance: 100

  remove-missed-arrows: true

  # cancel / remove
  prevent-item-dropping: remove

  # blocked commands during a fight
  blocked-commands:
    - spawn
    - lobby

  commands:
    on-start: ""
    on-end: ""
    on-win: ""
    on-lose: ""

  messages:
    on-start: ""
    on-end: ""
    on-win: ""
    on-lose: ""


gui:
  hotbar-slots:
    kit-selector: 0

  selector:
    kit:
      size: 27
      title: "<green>Wybierz kit"
    map:
      size: 54
      title: "<geen>Wybierz mape"
    fight:
      size: 54
      title: "<green>Wybierz walkę"

kits:
  jajko: 1


maps:
  rollback: true
  rollback-remove-endcrystals: true
  prevent-escaping: true


party:
  player-limit: 10
  chat-prefix: "@"

  messages:
    created: "<green>✔ Stworzyłeś party!"
    removed: "<red>✖ Party zostało usunięte!"


players:
  default-elo: 1000


queue:
  # ticks
  match-finder-interval: 10
  max-ping: 200

  elo-matching:
    strict:
      # seconds
      min-time: 0
      # +/- elo from queued player
      range: 10
    normal:
      min-time: 10
      range: 50
    lose:
      min-time: 20
      range: 100
    x-lose:
      min-time: 35
      range: 200
    every:
      min-time: 50
      range: 99999

  messages:
    enter: "<green>Oczekiwanie na gracza w kolejce..."
    leave: "<red>Opuściłeś kolejke!"
    searching: "<yellow>Szukanie graczy w zakresie <range> ELO!"


messages:
  jajo: ""
