fights:
  countdown:
    # seconds
    time: 5
    sound: NOTE_PLING
    message: ""

  # seconds
  end-teleport-wait: 3

  # -1 = disable
  # 0 = no teleport allowed
  max-teleport-distance: 100

  remove-missed-arrows: true

  prevent-item-dropping: true


  # blocked commands during a fight
  blocked-commands:
    - spawn
    - lobby

  commands:
    on-start: ""
    on-end: ""
    on-win: ""
    on-lose: ""

  messages:
    on-start: ""
    on-end: ""
    on-win: ""
    on-lose: ""

gui:
  hotbar: m
  jajko: 1

kits:
  jajko: 1

maps:
  rollback: true

party:
  player-limit: 10
  chat-prefix: "@"

players:
  default-elo: 1000

queue:
  # ticks
  match-finder-interval: 10
  max-ping: 200

messages:
  jajo: ""
