fights:
  countdown:
    # seconds
    time: 5
    sound: NOTE_PLING
    message: ""

  # seconds
  end-teleport-wait: 3

  # -1 = disable
  # 0 = no teleport allowed
  max-teleport-distance: 100

  remove-missed-arrows: true

  # cancel / remove
  prevent-item-dropping: remove

  # blocked commands during a fight
  blocked-commands:
    - spawn
    - lobby

  commands:
    on-start: ""
    on-end: ""
    on-win: ""
    on-lose: ""

  messages:
    on-start: ""
    on-end: ""
    on-win: ""
    on-lose: ""


# hotbar item actions:
#   OPEN_RANKED_FIGHT_SELECTOR
#   OPEN_KIT_EDITOR
#   OPEN_SPECTATOR_SELECTOR
#   LEAVE_QUEUE
#   CREATE_PARTY
#   LEAVE_PARTY
#   OPEN_PARTY_FIGHT_SELECTOR
#   OPEN_PARTY_SETTING_SELECTOR
#   SHOW_PARTY_INFO
#   COMMAND
hotbar:
  prevent-moving-hotbar-items: true

  lobby:
    queue-selector-item:
      slot: 1
      item:
        material: DIAMOND_SWORD
        name: "<#0BD0FB>Kolejka pojedynków"
      action: OPEN_RANKED_FIGHT_SELECTOR
    kit-editor-item:
      slot: 2
      item:
        material: BOOK
        name: "<#0BD0FB>Edycja zestawów"
      action: OPEN_KIT_EDITOR
    player-gui-item:
      slot: 5
      item:
        material: END_CRYSTAL
        name: "<#F477E7>Panel gracza"
      action: COMMAND
      command: "/#open player panel command"
    spectate-item:
      slot: 8
      item:
        material: ENDER_PEARL
        name: "<#0BD0FB>Obserwuj pojedynki"
      action: OPEN_SPECTATOR_SELECTOR
    party-create-item:
      slot: 9
      item:
        material: NOTE_BLOCK
        name: "<#0BD0FB>Stwórz party"
      action: CREATE_PARTY

  party:
    fight-selector-item:
      slot: 1
      item:
        material: DIAMOND_SWORD
        name: "<#0BD0FB>Walka party"
      action: OPEN_PARTY_FIGHT_SELECTOR
    settings-selector-item:
      slot: 2
      item:
        material: TRIPWIRE_HOOK
        name: "<#0BD0FB>Ustawienia party"
      action: OPEN_PARTY_SETTING_SELECTOR
    info-item:
      slot: 8
      item:
        material: PLAYER_HEAD
        name: "<#0BD0FB>Informacje o party"
      action: SHOW_PARTY_INFO
    leave-item:
      slot: 9
      item:
        material: BARRIER
        name: "<#0BD0FB>Opuść party"
      action: LEAVE_PARTY

  queued:
    quit-item:
      slot: 9
      item:
        material: BARRIER
        name: "<#0BD0FB>Usuń party"
      action: LEAVE_QUEUE


gui:
  # ticks
  selectors-update-interval: 20

  selectors:
    ranked-fight:
      # size = x*9
      size: 27
      title: "<gray>↓ <black>Kolejka pojedynków"
      items-lore:
        - "<grey>Graczy w kolejce: <#0BD0FB><kit_players_queued>"
        - "<grey>Graczy w pojedynku: <#0BD0FB><kit_players_fighting>"

    kit-editor:
      size: 27
      title: "<gray>↓ <black>Edycja zestawów"

    spectate:
      size: 54
      title: "<gray>↓ <black>Obserwuj walke"
      items-lore:
        - "<gray>Zestaw: <fight_kit_displayname>"
        - "<gray>Mapa: <fight_map_displayname>"
        - "<gray>Czas: <green><fight_duration_mm_ss>"

    party-fight:
      size: 54
      title: "<gray>↓ <black>Pojedynki party"

    party-settings:
      size: 27
      title: "<gray>↓ <black>Ustawienia party"


kits:
  jajko: 1


maps:
  rollback: true
  rollback-remove-endcrystals: true
  prevent-escaping: true


party:
  player-limit: 10
  chat-prefix: "@"

  messages:
    created: "<green>✔ Stworzyłeś party!"
    removed: "<red>✖ Party zostało usunięte!"


players:
  default-elo: 1000


queue:
  # ticks
  match-finder-interval: 10
  max-ping: 200

  elo-matching:
    strict:
      # seconds
      min-time: 0
      # +/- elo from queued player
      range: 10
    normal:
      min-time: 10
      range: 50
    lose:
      min-time: 20
      range: 100
    x-lose:
      min-time: 35
      range: 200
    every:
      min-time: 50
      range: 99999

  messages:
    enter: "<green>Oczekiwanie na gracza w kolejce..."
    leave: "<red>Opuściłeś kolejke!"
    searching: "<yellow>Szukanie graczy w zakresie <range> ELO!"


messages:
  jajo: ""
